import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { Metadata } from "next";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const menu = [
  { texto: "Users", url: "/page/user" },
  { texto: "Roles", url: "/page/roles" },
];

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
      </head>

      <body className={`bg-light ${inter.className}`}>
        <div className="container-fluid">
          <div className="row">
            <nav className="col-md-2 d-none d-md-block bg-light sidebar">
              <div className="position-sticky">
                <div className="list-group">
                  {menu.map((item, index) => (
                    <Link
                      href={item.url}
                      key={index}
                      className="list-group-item list-group-item-action">
                      {item.texto}
                    </Link>
                  ))}
                </div>
              </div>
            </nav>
            <main className="col-md-10 ms-sm-auto col-lg-10 px-md-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
